{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openfaas",
    "module": "model",
    "version": "2.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "model-2.1.1.jar",
          "url": "model-2.1.1.jar",
          "size": 4903,
          "sha512": "1fb480480e4e36580ee0ad03a5fa5283a0f6854d632694560fe2612707f6a5a560fc0c2838eb32133e6a3718ddea8a5d3aa60f78aea98fdb5420a454a96b8b8c",
          "sha256": "0e99e9a9233a24215867ba810a9067c83e1b05a96e49cdef9e9b10ad768d3877",
          "sha1": "c528f974fe0804435a13bbde53d6419572398ea6",
          "md5": "1a333c7ac7005e1be14e7a177d2cfaea"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "model-2.1.1.jar",
          "url": "model-2.1.1.jar",
          "size": 4903,
          "sha512": "1fb480480e4e36580ee0ad03a5fa5283a0f6854d632694560fe2612707f6a5a560fc0c2838eb32133e6a3718ddea8a5d3aa60f78aea98fdb5420a454a96b8b8c",
          "sha256": "0e99e9a9233a24215867ba810a9067c83e1b05a96e49cdef9e9b10ad768d3877",
          "sha1": "c528f974fe0804435a13bbde53d6419572398ea6",
          "md5": "1a333c7ac7005e1be14e7a177d2cfaea"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "model-2.1.1-javadoc.jar",
          "url": "model-2.1.1-javadoc.jar",
          "size": 94913,
          "sha512": "f6948961e56cc801a266518a54564b2b25b3ccb5c272a5bac0325542067bbd6ef1a1a518ba1449980528e0146272b4328e8c11286d763cc724b2de59db42fffa",
          "sha256": "c69c66209814c1b40a807ec03150076207687a4100c39ddb4d7a47c47314d12f",
          "sha1": "c10c6e00585b12cc1e3475f5f8faaf841793ed3b",
          "md5": "4c5ad138a6f7aea2070af0ae4f38d67b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "model-2.1.1-sources.jar",
          "url": "model-2.1.1-sources.jar",
          "size": 3793,
          "sha512": "cf4efa1c18c0f388fb65b3a5ce0de2907feab90120f4d3f1d347aaaaba9abcf17c7233c1359e534dea6c4c8ccdf8d1911964d0bb7601d3149adfd6f98bc63a3e",
          "sha256": "464325f68bbc10bceec7a05c0f2e6437dc78e6194f5836e0447843a383c86faa",
          "sha1": "f9ca5f0101a94d15a6031713661b438f2372449b",
          "md5": "d3b7e42d1bb7676caea4e864d4b4a8f6"
        }
      ]
    }
  ]
}
